// Generated by scripts/generate-plugin-route-hosts.ts from
// cloudflare_workers/plugin/wrangler.jsonc. Do not edit by hand.

/** Hostnames the plugin worker is routed on (custom domains and route patterns). */
export const PLUGIN_ROUTE_HOSTS: readonly string[] = [
  'api.capgo.app',
  'plugin.af.capgo.app',
  'plugin.as.capgo.app',
  'plugin.capgo.app',
  'plugin.dev.capgo.app',
  'plugin.eu.capgo.app',
  'plugin.hk.capgo.app',
  'plugin.jp.capgo.app',
  'plugin.me.capgo.app',
  'plugin.na.capgo.app',
  'plugin.oc.capgo.app',
  'plugin.preprod.capgo.app',
  'plugin.sa.capgo.app',
  'updater.capgo.com.cn',
  'updater.spencer.co',
]

/** Zones named explicitly by plugin routes (custom hostnames resolve through them). */
export const PLUGIN_ROUTE_ZONE_NAMES: readonly string[] = [
  'capgo.app',
]
