/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/accountDisabled': RouteRecordInfo<
      '/accountDisabled',
      '/accountDisabled',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/customers/credits': RouteRecordInfo<
      '/admin/dashboard/customers/credits',
      '/admin/dashboard/customers/credits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/customers/organizations': RouteRecordInfo<
      '/admin/dashboard/customers/organizations',
      '/admin/dashboard/customers/organizations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/onboarding/': RouteRecordInfo<
      '/admin/dashboard/onboarding/',
      '/admin/dashboard/onboarding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/onboarding/cohorts': RouteRecordInfo<
      '/admin/dashboard/onboarding/cohorts',
      '/admin/dashboard/onboarding/cohorts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/onboarding/frontend': RouteRecordInfo<
      '/admin/dashboard/onboarding/frontend',
      '/admin/dashboard/onboarding/frontend',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/onboarding/sources': RouteRecordInfo<
      '/admin/dashboard/onboarding/sources',
      '/admin/dashboard/onboarding/sources',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/platform/capacity': RouteRecordInfo<
      '/admin/dashboard/platform/capacity',
      '/admin/dashboard/platform/capacity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/platform/debug': RouteRecordInfo<
      '/admin/dashboard/platform/debug',
      '/admin/dashboard/platform/debug',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/platform/replication': RouteRecordInfo<
      '/admin/dashboard/platform/replication',
      '/admin/dashboard/platform/replication',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/product/builder': RouteRecordInfo<
      '/admin/dashboard/product/builder',
      '/admin/dashboard/product/builder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/product/cli': RouteRecordInfo<
      '/admin/dashboard/product/cli',
      '/admin/dashboard/product/cli',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/product/notifications': RouteRecordInfo<
      '/admin/dashboard/product/notifications',
      '/admin/dashboard/product/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/product/plugins': RouteRecordInfo<
      '/admin/dashboard/product/plugins',
      '/admin/dashboard/product/plugins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/product/updates': RouteRecordInfo<
      '/admin/dashboard/product/updates',
      '/admin/dashboard/product/updates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/pulse': RouteRecordInfo<
      '/admin/dashboard/pulse',
      '/admin/dashboard/pulse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/retention/': RouteRecordInfo<
      '/admin/dashboard/retention/',
      '/admin/dashboard/retention',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/retention/churn': RouteRecordInfo<
      '/admin/dashboard/retention/churn',
      '/admin/dashboard/retention/churn',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/retention/inactive': RouteRecordInfo<
      '/admin/dashboard/retention/inactive',
      '/admin/dashboard/retention/inactive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/revenue/': RouteRecordInfo<
      '/admin/dashboard/revenue/',
      '/admin/dashboard/revenue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/revenue/plans': RouteRecordInfo<
      '/admin/dashboard/revenue/plans',
      '/admin/dashboard/revenue/plans',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/revenue/risk': RouteRecordInfo<
      '/admin/dashboard/revenue/risk',
      '/admin/dashboard/revenue/risk',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard/revenue/upgrades': RouteRecordInfo<
      '/admin/dashboard/revenue/upgrades',
      '/admin/dashboard/revenue/upgrades',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ApiKeys': RouteRecordInfo<
      '/ApiKeys',
      '/apikeys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/[app]': RouteRecordInfo<
      '/app/[app]',
      '/app/:app',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].builds': RouteRecordInfo<
      '/app/[app].builds',
      '/app/:app/builds',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].bundle.[bundle]': RouteRecordInfo<
      '/app/[app].bundle.[bundle]',
      '/app/:app/bundle/:bundle',
      { app: ParamValue<true>, bundle: ParamValue<true> },
      { app: ParamValue<false>, bundle: ParamValue<false> },
      | never
    >,
    '/app/[app].bundle.[bundle].dependencies': RouteRecordInfo<
      '/app/[app].bundle.[bundle].dependencies',
      '/app/:app/bundle/:bundle/dependencies',
      { app: ParamValue<true>, bundle: ParamValue<true> },
      { app: ParamValue<false>, bundle: ParamValue<false> },
      | never
    >,
    '/app/[app].bundle.[bundle].history': RouteRecordInfo<
      '/app/[app].bundle.[bundle].history',
      '/app/:app/bundle/:bundle/history',
      { app: ParamValue<true>, bundle: ParamValue<true> },
      { app: ParamValue<false>, bundle: ParamValue<false> },
      | never
    >,
    '/app/[app].bundle.[bundle].manifest': RouteRecordInfo<
      '/app/[app].bundle.[bundle].manifest',
      '/app/:app/bundle/:bundle/manifest',
      { app: ParamValue<true>, bundle: ParamValue<true> },
      { app: ParamValue<false>, bundle: ParamValue<false> },
      | never
    >,
    '/app/[app].bundle.[bundle].preview': RouteRecordInfo<
      '/app/[app].bundle.[bundle].preview',
      '/app/:app/bundle/:bundle/preview',
      { app: ParamValue<true>, bundle: ParamValue<true> },
      { app: ParamValue<false>, bundle: ParamValue<false> },
      | never
    >,
    '/app/[app].bundles': RouteRecordInfo<
      '/app/[app].bundles',
      '/app/:app/bundles',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].bundles.new': RouteRecordInfo<
      '/app/[app].bundles.new',
      '/app/:app/bundles/new',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].channel.[channel]': RouteRecordInfo<
      '/app/[app].channel.[channel]',
      '/app/:app/channel/:channel',
      { app: ParamValue<true>, channel: ParamValue<true> },
      { app: ParamValue<false>, channel: ParamValue<false> },
      | never
    >,
    '/app/[app].channel.[channel].devices': RouteRecordInfo<
      '/app/[app].channel.[channel].devices',
      '/app/:app/channel/:channel/devices',
      { app: ParamValue<true>, channel: ParamValue<true> },
      { app: ParamValue<false>, channel: ParamValue<false> },
      | never
    >,
    '/app/[app].channel.[channel].history': RouteRecordInfo<
      '/app/[app].channel.[channel].history',
      '/app/:app/channel/:channel/history',
      { app: ParamValue<true>, channel: ParamValue<true> },
      { app: ParamValue<false>, channel: ParamValue<false> },
      | never
    >,
    '/app/[app].channel.[channel].preview': RouteRecordInfo<
      '/app/[app].channel.[channel].preview',
      '/app/:app/channel/:channel/preview',
      { app: ParamValue<true>, channel: ParamValue<true> },
      { app: ParamValue<false>, channel: ParamValue<false> },
      | never
    >,
    '/app/[app].channel.[channel].statistics': RouteRecordInfo<
      '/app/[app].channel.[channel].statistics',
      '/app/:app/channel/:channel/statistics',
      { app: ParamValue<true>, channel: ParamValue<true> },
      { app: ParamValue<false>, channel: ParamValue<false> },
      | never
    >,
    '/app/[app].channels': RouteRecordInfo<
      '/app/[app].channels',
      '/app/:app/channels',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].getting-started': RouteRecordInfo<
      '/app/[app].getting-started',
      '/app/:app/getting-started',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].device.[device]': RouteRecordInfo<
      '/app/[app].device.[device]',
      '/app/:app/device/:device',
      { app: ParamValue<true>, device: ParamValue<true> },
      { app: ParamValue<false>, device: ParamValue<false> },
      | never
    >,
    '/app/[app].device.[device].deployments': RouteRecordInfo<
      '/app/[app].device.[device].deployments',
      '/app/:app/device/:device/deployments',
      { app: ParamValue<true>, device: ParamValue<true> },
      { app: ParamValue<false>, device: ParamValue<false> },
      | never
    >,
    '/app/[app].device.[device].logs': RouteRecordInfo<
      '/app/[app].device.[device].logs',
      '/app/:app/device/:device/logs',
      { app: ParamValue<true>, device: ParamValue<true> },
      { app: ParamValue<false>, device: ParamValue<false> },
      | never
    >,
    '/app/[app].devices': RouteRecordInfo<
      '/app/[app].devices',
      '/app/:app/devices',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].notifications': RouteRecordInfo<
      '/app/[app].notifications',
      '/app/:app/notifications',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].observe.compatibility': RouteRecordInfo<
      '/app/[app].observe.compatibility',
      '/app/:app/observe/compatibility',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].observe.logs': RouteRecordInfo<
      '/app/[app].observe.logs',
      '/app/:app/observe/logs',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].observe.native': RouteRecordInfo<
      '/app/[app].observe.native',
      '/app/:app/observe/native',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].observe.plugins': RouteRecordInfo<
      '/app/[app].observe.plugins',
      '/app/:app/observe/plugins',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].observe.updater': RouteRecordInfo<
      '/app/[app].observe.updater',
      '/app/:app/observe/updater',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].settings': RouteRecordInfo<
      '/app/[app].settings',
      '/app/:app/settings',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/[app].settings.access': RouteRecordInfo<
      '/app/[app].settings.access',
      '/app/:app/settings/access',
      { app: ParamValue<true> },
      { app: ParamValue<false> },
      | never
    >,
    '/app/modules': RouteRecordInfo<
      '/app/modules',
      '/app/modules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/modules_test': RouteRecordInfo<
      '/app/modules_test',
      '/app/modules_test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/app/new': RouteRecordInfo<
      '/app/new',
      '/app/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/apps': RouteRecordInfo<
      '/apps',
      '/apps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/confirm-signup': RouteRecordInfo<
      '/confirm-signup',
      '/confirm-signup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/connect': RouteRecordInfo<
      '/connect',
      '/connect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/delete_account': RouteRecordInfo<
      '/delete_account',
      '/delete_account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demo_dialog': RouteRecordInfo<
      '/demo_dialog',
      '/demo_dialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/email-preferences': RouteRecordInfo<
      '/email-preferences',
      '/email-preferences',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forgot_password': RouteRecordInfo<
      '/forgot_password',
      '/forgot_password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invitation': RouteRecordInfo<
      '/invitation',
      '/invitation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/log-as/[userId]': RouteRecordInfo<
      '/log-as/[userId]',
      '/log-as/:userId',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/app': RouteRecordInfo<
      '/onboarding/app',
      '/onboarding/app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/invitation': RouteRecordInfo<
      '/onboarding/invitation',
      '/onboarding/invitation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/organization': RouteRecordInfo<
      '/onboarding/organization',
      '/onboarding/organization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/onboarding/set_password': RouteRecordInfo<
      '/onboarding/set_password',
      '/onboarding/set_password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/preview/bundle': RouteRecordInfo<
      '/preview/bundle',
      '/preview/bundle',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/preview/channel': RouteRecordInfo<
      '/preview/channel',
      '/preview/channel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/resend_email': RouteRecordInfo<
      '/resend_email',
      '/resend_email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scan': RouteRecordInfo<
      '/scan',
      '/scan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account/': RouteRecordInfo<
      '/settings/account/',
      '/settings/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account/ChangePassword': RouteRecordInfo<
      '/settings/account/ChangePassword',
      '/settings/account/change-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account/ManageTwoFactor': RouteRecordInfo<
      '/settings/account/ManageTwoFactor',
      '/settings/account/manage-2fa',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account/Notifications': RouteRecordInfo<
      '/settings/account/Notifications',
      '/settings/account/Notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/': RouteRecordInfo<
      '/settings/organization/',
      '/settings/organization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/ApiKeys': RouteRecordInfo<
      '/settings/organization/ApiKeys',
      '/settings/organization/api-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/ApiKeys.[id]': RouteRecordInfo<
      '/settings/organization/ApiKeys.[id]',
      '/settings/organization/api-keys/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings/organization/Security': RouteRecordInfo<
      '/settings/organization/Security',
      '/settings/organization/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/AuditLogs': RouteRecordInfo<
      '/settings/organization/AuditLogs',
      '/settings/organization/AuditLogs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Credits': RouteRecordInfo<
      '/settings/organization/Credits',
      '/settings/organization/Credits',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/DeleteOrgDialog': RouteRecordInfo<
      '/settings/organization/DeleteOrgDialog',
      '/settings/organization/DeleteOrgDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Groups': RouteRecordInfo<
      '/settings/organization/Groups',
      '/settings/organization/Groups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Groups.[id]': RouteRecordInfo<
      '/settings/organization/Groups.[id]',
      '/settings/organization/Groups/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings/organization/Members': RouteRecordInfo<
      '/settings/organization/Members',
      '/settings/organization/Members',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Notifications': RouteRecordInfo<
      '/settings/organization/Notifications',
      '/settings/organization/Notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Plans': RouteRecordInfo<
      '/settings/organization/Plans',
      '/settings/organization/Plans',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Usage': RouteRecordInfo<
      '/settings/organization/Usage',
      '/settings/organization/Usage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/organization/Webhooks': RouteRecordInfo<
      '/settings/organization/Webhooks',
      '/settings/organization/Webhooks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sso-callback': RouteRecordInfo<
      '/sso-callback',
      '/sso-callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Webhooks': RouteRecordInfo<
      '/Webhooks',
      '/Webhooks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/accountDisabled.vue': {
      routes:
        | '/accountDisabled'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/customers/credits.vue': {
      routes:
        | '/admin/dashboard/customers/credits'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/customers/organizations.vue': {
      routes:
        | '/admin/dashboard/customers/organizations'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/onboarding/index.vue': {
      routes:
        | '/admin/dashboard/onboarding/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/onboarding/cohorts.vue': {
      routes:
        | '/admin/dashboard/onboarding/cohorts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/onboarding/frontend.vue': {
      routes:
        | '/admin/dashboard/onboarding/frontend'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/onboarding/sources.vue': {
      routes:
        | '/admin/dashboard/onboarding/sources'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/platform/capacity.vue': {
      routes:
        | '/admin/dashboard/platform/capacity'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/platform/debug.vue': {
      routes:
        | '/admin/dashboard/platform/debug'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/platform/replication.vue': {
      routes:
        | '/admin/dashboard/platform/replication'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/product/builder.vue': {
      routes:
        | '/admin/dashboard/product/builder'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/product/cli.vue': {
      routes:
        | '/admin/dashboard/product/cli'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/product/notifications.vue': {
      routes:
        | '/admin/dashboard/product/notifications'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/product/plugins.vue': {
      routes:
        | '/admin/dashboard/product/plugins'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/product/updates.vue': {
      routes:
        | '/admin/dashboard/product/updates'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/pulse.vue': {
      routes:
        | '/admin/dashboard/pulse'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/retention/index.vue': {
      routes:
        | '/admin/dashboard/retention/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/retention/churn.vue': {
      routes:
        | '/admin/dashboard/retention/churn'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/retention/inactive.vue': {
      routes:
        | '/admin/dashboard/retention/inactive'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/revenue/index.vue': {
      routes:
        | '/admin/dashboard/revenue/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/revenue/plans.vue': {
      routes:
        | '/admin/dashboard/revenue/plans'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/revenue/risk.vue': {
      routes:
        | '/admin/dashboard/revenue/risk'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/dashboard/revenue/upgrades.vue': {
      routes:
        | '/admin/dashboard/revenue/upgrades'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ApiKeys.vue': {
      routes:
        | '/ApiKeys'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/[app].vue': {
      routes:
        | '/app/[app]'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].builds.vue': {
      routes:
        | '/app/[app].builds'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].bundle.[bundle].vue': {
      routes:
        | '/app/[app].bundle.[bundle]'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'bundle'
    }
    'src/pages/app/[app].bundle.[bundle].dependencies.vue': {
      routes:
        | '/app/[app].bundle.[bundle].dependencies'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'bundle'
    }
    'src/pages/app/[app].bundle.[bundle].history.vue': {
      routes:
        | '/app/[app].bundle.[bundle].history'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'bundle'
    }
    'src/pages/app/[app].bundle.[bundle].manifest.vue': {
      routes:
        | '/app/[app].bundle.[bundle].manifest'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'bundle'
    }
    'src/pages/app/[app].bundle.[bundle].preview.vue': {
      routes:
        | '/app/[app].bundle.[bundle].preview'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'bundle'
    }
    'src/pages/app/[app].bundles.vue': {
      routes:
        | '/app/[app].bundles'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].bundles.new.vue': {
      routes:
        | '/app/[app].bundles.new'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].channel.[channel].vue': {
      routes:
        | '/app/[app].channel.[channel]'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'channel'
    }
    'src/pages/app/[app].channel.[channel].devices.vue': {
      routes:
        | '/app/[app].channel.[channel].devices'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'channel'
    }
    'src/pages/app/[app].channel.[channel].history.vue': {
      routes:
        | '/app/[app].channel.[channel].history'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'channel'
    }
    'src/pages/app/[app].channel.[channel].preview.vue': {
      routes:
        | '/app/[app].channel.[channel].preview'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'channel'
    }
    'src/pages/app/[app].channel.[channel].statistics.vue': {
      routes:
        | '/app/[app].channel.[channel].statistics'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'channel'
    }
    'src/pages/app/[app].channels.vue': {
      routes:
        | '/app/[app].channels'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].getting-started.vue': {
      routes:
        | '/app/[app].getting-started'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].device.[device].vue': {
      routes:
        | '/app/[app].device.[device]'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'device'
    }
    'src/pages/app/[app].device.[device].deployments.vue': {
      routes:
        | '/app/[app].device.[device].deployments'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'device'
    }
    'src/pages/app/[app].device.[device].logs.vue': {
      routes:
        | '/app/[app].device.[device].logs'
      views:
        | never
      pathParamNames:
        | 'app'
        | 'device'
    }
    'src/pages/app/[app].devices.vue': {
      routes:
        | '/app/[app].devices'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].notifications.vue': {
      routes:
        | '/app/[app].notifications'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].observe.compatibility.vue': {
      routes:
        | '/app/[app].observe.compatibility'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].observe.logs.vue': {
      routes:
        | '/app/[app].observe.logs'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].observe.native.vue': {
      routes:
        | '/app/[app].observe.native'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].observe.plugins.vue': {
      routes:
        | '/app/[app].observe.plugins'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].observe.updater.vue': {
      routes:
        | '/app/[app].observe.updater'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].settings.vue': {
      routes:
        | '/app/[app].settings'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/[app].settings.access.vue': {
      routes:
        | '/app/[app].settings.access'
      views:
        | never
      pathParamNames:
        | 'app'
    }
    'src/pages/app/modules.vue': {
      routes:
        | '/app/modules'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/modules_test.vue': {
      routes:
        | '/app/modules_test'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/app/new.vue': {
      routes:
        | '/app/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/apps.vue': {
      routes:
        | '/apps'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/confirm-signup.vue': {
      routes:
        | '/confirm-signup'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/connect.vue': {
      routes:
        | '/connect'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/delete_account.vue': {
      routes:
        | '/delete_account'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/demo_dialog.vue': {
      routes:
        | '/demo_dialog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/email-preferences.vue': {
      routes:
        | '/email-preferences'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/forgot_password.vue': {
      routes:
        | '/forgot_password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/invitation.vue': {
      routes:
        | '/invitation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/log-as/[userId].vue': {
      routes:
        | '/log-as/[userId]'
      views:
        | never
      pathParamNames:
        | 'userId'
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/onboarding/app.vue': {
      routes:
        | '/onboarding/app'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/onboarding/invitation.vue': {
      routes:
        | '/onboarding/invitation'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/onboarding/organization.vue': {
      routes:
        | '/onboarding/organization'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/onboarding/set_password.vue': {
      routes:
        | '/onboarding/set_password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/preview/bundle.vue': {
      routes:
        | '/preview/bundle'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/preview/channel.vue': {
      routes:
        | '/preview/channel'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/resend_email.vue': {
      routes:
        | '/resend_email'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/scan.vue': {
      routes:
        | '/scan'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/account/index.vue': {
      routes:
        | '/settings/account/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/account/ChangePassword.vue': {
      routes:
        | '/settings/account/ChangePassword'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/account/ManageTwoFactor.vue': {
      routes:
        | '/settings/account/ManageTwoFactor'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/account/Notifications.vue': {
      routes:
        | '/settings/account/Notifications'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/organization/index.vue': {
      routes:
        | '/settings/organization/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/organization/ApiKeys.vue': {
      routes:
        | '/settings/organization/ApiKeys'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/organization/ApiKeys.[id].vue': {
      routes:
        | '/settings/organization/ApiKeys.[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/settings/organization/Security.vue': {
      routes:
        | '/settings/organization/Security'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/organization/AuditLogs.vue': {
      routes:
        | '/settings/organization/AuditLogs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/organization/Credits.vue': {
      routes:
        | '/settings/organization/Credits'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/organization/DeleteOrgDialog.vue': {
      routes:
        | '/settings/organization/DeleteOrgDialog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/organization/Groups.vue': {
      routes:
        | '/settings/organization/Groups'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/organization/Groups.[id].vue': {
      routes:
        | '/settings/organization/Groups.[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/settings/organization/Members.vue': {
      routes:
        | '/settings/organization/Members'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/organization/Notifications.vue': {
      routes:
        | '/settings/organization/Notifications'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/organization/Plans.vue': {
      routes:
        | '/settings/organization/Plans'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/organization/Usage.vue': {
      routes:
        | '/settings/organization/Usage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/organization/Webhooks.vue': {
      routes:
        | '/settings/organization/Webhooks'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/sso-callback.vue': {
      routes:
        | '/sso-callback'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Webhooks.vue': {
      routes:
        | '/Webhooks'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
