-- Canceled-org retention lifecycle:
--   85 days: warn that bundles will be deleted in 5 days (Bento / tracking)
--   90 days: soft-delete bundles (existing) + warn that apps will be deleted in 5 days
--   95 days: delete apps and archive app_id + creator email into old_apps
--
-- Alerts are queued to pgmq and delivered by the canceled_org_retention_alerts
-- edge trigger. Dedup uses public.notifications once-claims so daily cron
-- catch-up does not re-queue forever.

-- Permanent archive of apps removed by the 95-day unpaid retention path.
CREATE TABLE IF NOT EXISTS public.old_apps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_id character varying NOT NULL,
  email text NOT NULL,
  owner_org uuid NOT NULL,
  user_id uuid,
  app_created_at timestamp with time zone,
  deleted_at timestamp with time zone DEFAULT now() NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT old_apps_app_id_owner_org_key UNIQUE (app_id, owner_org)
);

ALTER TABLE public.old_apps OWNER TO postgres;

COMMENT ON TABLE public.old_apps IS
  'Archive of apps deleted after the unpaid/canceled retention window (95 days). Keeps app_id and creator email for support memory; not purged by delete_old_deleted_apps.';

COMMENT ON COLUMN public.old_apps.email IS
  'Email of the app creator (public.users via apps.user_id), falling back to org management_email.';

COMMENT ON COLUMN public.old_apps.app_created_at IS
  'Original apps.created_at at archival time.';

CREATE INDEX IF NOT EXISTS old_apps_email_idx
  ON public.old_apps (email);

CREATE INDEX IF NOT EXISTS old_apps_deleted_at_idx
  ON public.old_apps (deleted_at);

ALTER TABLE public.old_apps ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Deny all access on old_apps" ON public.old_apps;
CREATE POLICY "Deny all access on old_apps"
  ON public.old_apps
  USING (false)
  WITH CHECK (false);

GRANT SELECT, INSERT, REFERENCES, DELETE, TRIGGER, TRUNCATE, UPDATE ON TABLE public.old_apps TO anon;
GRANT SELECT, INSERT, REFERENCES, DELETE, TRIGGER, TRUNCATE, UPDATE ON TABLE public.old_apps TO authenticated;
GRANT ALL ON TABLE public.old_apps TO service_role;
GRANT ALL ON SEQUENCE public.old_apps_id_seq TO anon;
GRANT ALL ON SEQUENCE public.old_apps_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.old_apps_id_seq TO service_role;

-- Parameterized eligibility: canceled/deleted orgs past N days of end-of-access.
CREATE OR REPLACE FUNCTION public.canceled_org_ids_past_grace(p_days integer)
RETURNS SETOF uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT o.id
  FROM public.stripe_info AS si
  JOIN public.orgs AS o ON o.customer_id = si.customer_id
  WHERE si.status IN ('canceled', 'deleted')
    AND GREATEST(si.canceled_at, si.subscription_anchor_end, si.trial_at)
      <= pg_catalog.now() - make_interval(days => GREATEST(0, COALESCE(p_days, 0)));
$$;

ALTER FUNCTION public.canceled_org_ids_past_grace(integer) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.canceled_org_ids_past_grace(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.canceled_org_ids_past_grace(integer) FROM anon;
REVOKE ALL ON FUNCTION public.canceled_org_ids_past_grace(integer) FROM authenticated;
GRANT ALL ON FUNCTION public.canceled_org_ids_past_grace(integer) TO service_role;

COMMENT ON FUNCTION public.canceled_org_ids_past_grace(integer) IS
  'Org ids whose stripe_info is canceled/deleted and GREATEST(canceled_at, subscription_anchor_end, trial_at) is older than p_days.';

-- Keep the existing 90-day helper as a thin wrapper for call sites / tests.
CREATE OR REPLACE FUNCTION public.long_canceled_org_ids()
RETURNS SETOF uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT public.canceled_org_ids_past_grace(90);
$$;

ALTER FUNCTION public.long_canceled_org_ids() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.long_canceled_org_ids() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.long_canceled_org_ids() FROM anon;
REVOKE ALL ON FUNCTION public.long_canceled_org_ids() FROM authenticated;
GRANT ALL ON FUNCTION public.long_canceled_org_ids() TO service_role;

COMMENT ON FUNCTION public.long_canceled_org_ids() IS
  'Org ids whose stripe_info is canceled/deleted and GREATEST(canceled_at, subscription_anchor_end, trial_at) is older than 90 days.';

-- Queue retention warning events (85d bundles / 90d apps). Dedup via notifications.
CREATE OR REPLACE FUNCTION public.queue_canceled_org_retention_alerts(
  p_alert_type text,
  p_min_days integer,
  p_batch_size integer DEFAULT 500
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_batch_size integer := GREATEST(1, COALESCE(p_batch_size, 500));
  v_event text;
  v_queued bigint := 0;
  org_record RECORD;
BEGIN
  IF p_alert_type = 'bundles_deletion_warning' THEN
    v_event := 'org:bundles_will_be_deleted';
  ELSIF p_alert_type = 'app_deletion_warning' THEN
    v_event := 'org:apps_will_be_deleted';
  ELSE
    RAISE EXCEPTION 'unsupported retention alert type: %', p_alert_type;
  END IF;

  FOR org_record IN
    SELECT
      o.id AS org_id,
      o.name AS org_name,
      o.management_email,
      GREATEST(si.canceled_at, si.subscription_anchor_end, si.trial_at) AS access_end,
      COALESCE(
        (
          SELECT jsonb_agg(a.app_id ORDER BY a.app_id)
          FROM public.apps AS a
          WHERE a.owner_org = o.id
        ),
        '[]'::jsonb
      ) AS app_ids
    FROM public.stripe_info AS si
    JOIN public.orgs AS o ON o.customer_id = si.customer_id
    WHERE si.status IN ('canceled', 'deleted')
      AND GREATEST(si.canceled_at, si.subscription_anchor_end, si.trial_at)
        <= pg_catalog.now() - make_interval(days => GREATEST(0, COALESCE(p_min_days, 0)))
      AND EXISTS (
        SELECT 1
        FROM public.apps AS a
        WHERE a.owner_org = o.id
      )
      AND NOT EXISTS (
        SELECT 1
        FROM public.notifications AS n
        WHERE n.owner_org = o.id
          AND n.event = v_event
          AND n.uniq_id = (
            'retention:'
            || p_alert_type
            || ':'
            || to_char(
              GREATEST(si.canceled_at, si.subscription_anchor_end, si.trial_at) AT TIME ZONE 'UTC',
              'YYYY-MM-DD'
            )
          )
      )
    ORDER BY o.id
    LIMIT v_batch_size
  LOOP
    PERFORM pgmq.send(
      'canceled_org_retention_alerts',
      jsonb_build_object(
        'function_name', 'canceled_org_retention_alerts',
        'function_type', 'cloudflare',
        'payload', jsonb_build_object(
          'org_id', org_record.org_id,
          'org_name', org_record.org_name,
          'management_email', org_record.management_email,
          'alert_type', p_alert_type,
          'access_end', org_record.access_end,
          'days_until_deletion', 5,
          'app_ids', org_record.app_ids
        )
      )
    );
    v_queued := v_queued + 1;
  END LOOP;

  IF v_queued > 0 THEN
    RAISE NOTICE
      'queue_canceled_org_retention_alerts: type=% queued=%',
      p_alert_type,
      v_queued;
  END IF;

  RETURN v_queued;
END;
$$;

ALTER FUNCTION public.queue_canceled_org_retention_alerts(text, integer, integer) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.queue_canceled_org_retention_alerts(text, integer, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.queue_canceled_org_retention_alerts(text, integer, integer) FROM anon;
REVOKE ALL ON FUNCTION public.queue_canceled_org_retention_alerts(text, integer, integer) FROM authenticated;
GRANT ALL ON FUNCTION public.queue_canceled_org_retention_alerts(text, integer, integer) TO service_role;

COMMENT ON FUNCTION public.queue_canceled_org_retention_alerts(text, integer, integer) IS
  'Queues once-per-cancel-cycle Bento/tracking warnings for canceled orgs past p_min_days (bundles at 85, apps at 90). Skips orgs already claimed in notifications.';

-- Hard-delete apps for orgs past the 95-day unpaid window; archive to old_apps first.
CREATE OR REPLACE FUNCTION public.delete_apps_for_long_canceled_orgs(
  p_batch_size integer DEFAULT 500
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_batch_size integer := GREATEST(1, COALESCE(p_batch_size, 500));
  deleted_count bigint := 0;
BEGIN
  WITH candidates AS (
    SELECT
      a.app_id,
      a.owner_org,
      a.user_id,
      a.created_at AS app_created_at,
      COALESCE(u.email::text, o.management_email) AS email
    FROM public.apps AS a
    JOIN public.orgs AS o ON o.id = a.owner_org
    LEFT JOIN public.users AS u ON u.id = a.user_id
    WHERE a.owner_org IN (SELECT public.canceled_org_ids_past_grace(95))
    ORDER BY a.app_id
    LIMIT v_batch_size
  ),
  archived AS (
    INSERT INTO public.old_apps (app_id, email, owner_org, user_id, app_created_at)
    SELECT
      c.app_id,
      c.email,
      c.owner_org,
      c.user_id,
      c.app_created_at
    FROM candidates AS c
    ON CONFLICT (app_id, owner_org) DO UPDATE
    SET
      email = EXCLUDED.email,
      user_id = EXCLUDED.user_id,
      app_created_at = EXCLUDED.app_created_at,
      deleted_at = pg_catalog.now()
    RETURNING old_apps.app_id
  ),
  deleted AS (
    DELETE FROM public.apps AS a
    USING candidates AS c
    WHERE a.app_id = c.app_id
      AND a.owner_org = c.owner_org
    RETURNING a.app_id
  )
  SELECT COUNT(*) INTO deleted_count FROM deleted;

  IF deleted_count > 0 THEN
    RAISE NOTICE
      'delete_apps_for_long_canceled_orgs: deleted_apps=%',
      deleted_count;
  END IF;

  RETURN deleted_count;
END;
$$;

ALTER FUNCTION public.delete_apps_for_long_canceled_orgs(integer) OWNER TO postgres;
REVOKE ALL ON FUNCTION public.delete_apps_for_long_canceled_orgs(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.delete_apps_for_long_canceled_orgs(integer) FROM anon;
REVOKE ALL ON FUNCTION public.delete_apps_for_long_canceled_orgs(integer) FROM authenticated;
GRANT ALL ON FUNCTION public.delete_apps_for_long_canceled_orgs(integer) TO service_role;

COMMENT ON FUNCTION public.delete_apps_for_long_canceled_orgs(integer) IS
  'Deletes apps for orgs past the 95-day canceled grace window after archiving app_id + creator email into old_apps. Bounded by p_batch_size.';

-- Daily retention orchestrator: warnings + version soft-delete + app delete + audit purge.
CREATE OR REPLACE FUNCTION public.cleanup_long_canceled_org_data()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  -- 85 days: warn that bundles will be deleted in 5 days.
  PERFORM public.queue_canceled_org_retention_alerts('bundles_deletion_warning', 85);
  -- 90 days: soft-delete bundles for long-canceled orgs.
  PERFORM public.soft_delete_versions_for_long_canceled_orgs();
  -- 90 days: warn that apps will be deleted in 5 days.
  PERFORM public.queue_canceled_org_retention_alerts('app_deletion_warning', 90);
  -- 95 days: delete apps and keep app_id + creator email in old_apps.
  PERFORM public.delete_apps_for_long_canceled_orgs();
  -- Purge audit logs for orgs past the 90-day grace window.
  PERFORM public.cleanup_audit_logs_for_long_canceled_orgs();
END;
$$;

ALTER FUNCTION public.cleanup_long_canceled_org_data() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.cleanup_long_canceled_org_data() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cleanup_long_canceled_org_data() FROM anon;
REVOKE ALL ON FUNCTION public.cleanup_long_canceled_org_data() FROM authenticated;
GRANT ALL ON FUNCTION public.cleanup_long_canceled_org_data() TO service_role;

COMMENT ON FUNCTION public.cleanup_long_canceled_org_data() IS
  'Daily canceled-org retention: 85d bundle warning, 90d soft-delete versions + app warning, 95d delete apps into old_apps, then purge audit_logs. Steps are batch/runtime bounded.';

-- Alert delivery queue + high-frequency drain registration.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pgmq.list_queues()
    WHERE queue_name = 'canceled_org_retention_alerts'
  ) THEN
    PERFORM pgmq.create('canceled_org_retention_alerts');
  END IF;
END;
$$;

DO $$
DECLARE
  high_frequency_task_type public.cron_task_type;
  high_frequency_target jsonb;
BEGIN
  SELECT cron.task_type, cron.target::jsonb
  INTO high_frequency_task_type, high_frequency_target
  FROM public.cron_tasks AS cron
  WHERE cron.name = 'high_frequency_queues'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Required cron task high_frequency_queues is missing';
  END IF;

  IF high_frequency_task_type
    IS DISTINCT FROM 'function_queue'::public.cron_task_type THEN
    RAISE EXCEPTION 'Cron task high_frequency_queues must use task type function_queue';
  END IF;

  IF pg_catalog.jsonb_typeof(high_frequency_target)
    IS DISTINCT FROM 'array' THEN
    RAISE EXCEPTION 'Cron task high_frequency_queues target must be a JSON array';
  END IF;

  IF NOT (high_frequency_target ? 'canceled_org_retention_alerts') THEN
    UPDATE public.cron_tasks
    SET
      target = (
        high_frequency_target || '["canceled_org_retention_alerts"]'::jsonb
      )::text,
      updated_at = pg_catalog.now()
    WHERE name = 'high_frequency_queues';
  END IF;
END;
$$;

UPDATE public.cron_tasks
SET
  description = 'Canceled-org retention: 85d bundle warn, 90d soft-delete + app warn, 95d delete apps into old_apps, purge audit logs',
  updated_at = now()
WHERE name = 'canceled_org_version_cleanup';
