-- Builder pool capacity as an event log (+/− workers) plus build run intervals
-- on build_requests. Hourly free/used is reconstructed from these events —
-- no polling cron snapshots.

ALTER TABLE public.build_requests
  ADD COLUMN IF NOT EXISTS started_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS completed_at timestamp with time zone;

COMMENT ON COLUMN public.build_requests.started_at IS
  'Builder-reported job start (UTC). Used for capacity reconstruction.';
COMMENT ON COLUMN public.build_requests.completed_at IS
  'Builder-reported job completion (UTC). Used for capacity reconstruction.';

CREATE INDEX IF NOT EXISTS idx_build_requests_started_at
  ON public.build_requests USING btree (started_at)
  WHERE started_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_build_requests_run_interval
  ON public.build_requests USING btree (started_at, completed_at)
  WHERE started_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.builder_capacity_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  workers_total integer NOT NULL,
  delta integer NOT NULL,
  source text NOT NULL DEFAULT 'sync',
  CONSTRAINT builder_capacity_events_workers_total_check CHECK (workers_total >= 0),
  CONSTRAINT builder_capacity_events_source_check CHECK (
    char_length(source) > 0
    AND char_length(source) <= 64
  )
);

ALTER TABLE public.builder_capacity_events OWNER TO postgres;

COMMENT ON TABLE public.builder_capacity_events IS
  'Absolute worker pool size over time. delta is workers_total - previous workers_total.';

CREATE INDEX IF NOT EXISTS idx_builder_capacity_events_created_at
  ON public.builder_capacity_events USING btree (created_at DESC);

ALTER TABLE public.builder_capacity_events ENABLE ROW LEVEL SECURITY;

-- System-managed: only service_role may read/write. Platform admin stats use
-- the service-role path in admin_stats, never PostgREST user context.
CREATE POLICY "Deny all authenticated on builder_capacity_events"
  ON public.builder_capacity_events
  AS RESTRICTIVE
  FOR ALL
  TO authenticated, anon
  USING (false)
  WITH CHECK (false);

CREATE POLICY "Service role manages builder_capacity_events"
  ON public.builder_capacity_events
  TO service_role
  USING (true)
  WITH CHECK (true);

GRANT ALL ON TABLE public.builder_capacity_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.builder_capacity_events_id_seq TO service_role;
REVOKE ALL ON TABLE public.builder_capacity_events FROM PUBLIC;
REVOKE ALL ON TABLE public.builder_capacity_events FROM anon;
REVOKE ALL ON TABLE public.builder_capacity_events FROM authenticated;
