CREATE TABLE public.user_onboarding (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text NOT NULL,
  user_id uuid,
  details jsonb,
  source text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_onboarding_type_not_empty CHECK (btrim(type) <> ''),
  CONSTRAINT user_onboarding_user_id_required CHECK (user_id IS NOT NULL OR type = 'feature_date'),
  CONSTRAINT user_onboarding_source_allowed CHECK (source IS NULL OR source IN ('dashboard', 'CLI')),
  CONSTRAINT user_onboarding_source_required CHECK (source IS NOT NULL OR type = 'feature_date'),
  CONSTRAINT user_onboarding_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    ON DELETE CASCADE
);

ALTER TABLE public.user_onboarding ENABLE ROW LEVEL SECURITY;

-- The primary key supplies the requested index on id.
CREATE INDEX user_onboarding_user_id_idx
  ON public.user_onboarding (user_id);

CREATE INDEX user_onboarding_user_id_type_idx
  ON public.user_onboarding (user_id, type);

CREATE INDEX user_onboarding_feature_date_feature_idx
  ON public.user_onboarding ((details ->> 'feature'))
  WHERE type = 'feature_date';

CREATE OR REPLACE FUNCTION public.set_user_onboarding_source()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NEW.type = 'feature_date' THEN
    NEW.source := NULL;
  ELSIF pg_catalog.current_setting('role', true) = 'service_role' THEN
    -- Trusted internal callers have no user authentication method, so they must
    -- explicitly identify which supported source initiated the write.
    NEW.source := NEW.source;
  ELSIF (SELECT auth.uid()) IS NOT NULL THEN
    NEW.source := 'dashboard';
  ELSIF public.get_user_id(public.get_apikey_header()) IS NOT NULL THEN
    NEW.source := 'CLI';
  ELSE
    NEW.source := NULL;
  END IF;

  RETURN NEW;
END;
$$;

ALTER FUNCTION public.set_user_onboarding_source() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.set_user_onboarding_source() FROM PUBLIC;

CREATE TRIGGER user_onboarding_set_source
  BEFORE INSERT OR UPDATE OF type, source ON public.user_onboarding
  FOR EACH ROW
  EXECUTE FUNCTION public.set_user_onboarding_source();

GRANT SELECT, INSERT ON TABLE public.user_onboarding TO anon, authenticated;
GRANT ALL ON TABLE public.user_onboarding TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.user_onboarding_id_seq TO anon, authenticated, service_role;

CREATE POLICY "Users can select own onboarding and public feature dates"
  ON public.user_onboarding
  FOR SELECT
  TO anon, authenticated
  USING (
    (type = 'feature_date' AND user_id IS NULL)
    OR user_id = COALESCE(
      (SELECT auth.uid()),
      (SELECT public.get_user_id(public.get_apikey_header()))
    )
  );

CREATE POLICY "Users can insert own onboarding entries"
  ON public.user_onboarding
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (
    type <> 'feature_date'
    AND user_id = COALESCE(
      (SELECT auth.uid()),
      (SELECT public.get_user_id(public.get_apikey_header()))
    )
  );

CREATE POLICY "Deny user onboarding updates"
  ON public.user_onboarding
  AS RESTRICTIVE
  FOR UPDATE
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

CREATE POLICY "Deny user onboarding deletes"
  ON public.user_onboarding
  AS RESTRICTIVE
  FOR DELETE
  TO anon, authenticated
  USING (false);
