-- Remote MCP OAuth state. Service-role only. Clients never read these tables.
-- Access tokens are random secrets; the plaintext Capgo API key stays on apikeys.

CREATE TABLE public.mcp_oauth_clients (
  client_id text PRIMARY KEY,
  client_name text NOT NULL,
  redirect_uris jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mcp_oauth_clients_redirect_uris_array CHECK (jsonb_typeof(redirect_uris) = 'array')
);

CREATE TABLE public.mcp_oauth_codes (
  code_hash text PRIMARY KEY,
  client_id text NOT NULL REFERENCES public.mcp_oauth_clients (client_id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  apikey_id bigint NOT NULL REFERENCES public.apikeys (id) ON DELETE CASCADE,
  redirect_uri text NOT NULL,
  code_challenge text NOT NULL,
  resource text NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz
);

CREATE INDEX mcp_oauth_codes_expires_at_idx ON public.mcp_oauth_codes (expires_at);

CREATE TABLE public.mcp_oauth_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_token_hash text NOT NULL UNIQUE,
  refresh_token_hash text NOT NULL UNIQUE,
  client_id text NOT NULL
    REFERENCES public.mcp_oauth_clients (client_id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  apikey_id bigint NOT NULL REFERENCES public.apikeys (id) ON DELETE CASCADE,
  access_expires_at timestamptz NOT NULL,
  refresh_expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX mcp_oauth_tokens_apikey_id_idx
  ON public.mcp_oauth_tokens (apikey_id);
CREATE INDEX mcp_oauth_tokens_refresh_expires_at_idx
  ON public.mcp_oauth_tokens (refresh_expires_at);

ALTER TABLE public.mcp_oauth_clients OWNER TO postgres;
ALTER TABLE public.mcp_oauth_codes OWNER TO postgres;
ALTER TABLE public.mcp_oauth_tokens OWNER TO postgres;

ALTER TABLE public.mcp_oauth_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mcp_oauth_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mcp_oauth_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Deny select on mcp_oauth_clients" ON public.mcp_oauth_clients AS RESTRICTIVE FOR SELECT TO authenticated, anon USING (false);
CREATE POLICY "Deny insert on mcp_oauth_clients" ON public.mcp_oauth_clients AS RESTRICTIVE FOR INSERT TO authenticated, anon WITH CHECK (false);
CREATE POLICY "Deny update on mcp_oauth_clients" ON public.mcp_oauth_clients AS RESTRICTIVE FOR UPDATE TO authenticated, anon USING (false);
CREATE POLICY "Deny delete on mcp_oauth_clients" ON public.mcp_oauth_clients AS RESTRICTIVE FOR DELETE TO authenticated, anon USING (false);

CREATE POLICY "Deny select on mcp_oauth_codes" ON public.mcp_oauth_codes AS RESTRICTIVE FOR SELECT TO authenticated, anon USING (false);
CREATE POLICY "Deny insert on mcp_oauth_codes" ON public.mcp_oauth_codes AS RESTRICTIVE FOR INSERT TO authenticated, anon WITH CHECK (false);
CREATE POLICY "Deny update on mcp_oauth_codes" ON public.mcp_oauth_codes AS RESTRICTIVE FOR UPDATE TO authenticated, anon USING (false);
CREATE POLICY "Deny delete on mcp_oauth_codes" ON public.mcp_oauth_codes AS RESTRICTIVE FOR DELETE TO authenticated, anon USING (false);

CREATE POLICY "Deny select on mcp_oauth_tokens" ON public.mcp_oauth_tokens AS RESTRICTIVE FOR SELECT TO authenticated, anon USING (false);
CREATE POLICY "Deny insert on mcp_oauth_tokens" ON public.mcp_oauth_tokens AS RESTRICTIVE FOR INSERT TO authenticated, anon WITH CHECK (false);
CREATE POLICY "Deny update on mcp_oauth_tokens" ON public.mcp_oauth_tokens AS RESTRICTIVE FOR UPDATE TO authenticated, anon USING (false);
CREATE POLICY "Deny delete on mcp_oauth_tokens" ON public.mcp_oauth_tokens AS RESTRICTIVE FOR DELETE TO authenticated, anon USING (false);

REVOKE ALL ON TABLE public.mcp_oauth_clients FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.mcp_oauth_codes FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.mcp_oauth_tokens FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.mcp_oauth_tokens_id_seq FROM PUBLIC, anon, authenticated;

GRANT ALL ON TABLE public.mcp_oauth_clients TO service_role;
GRANT ALL ON TABLE public.mcp_oauth_codes TO service_role;
GRANT ALL ON TABLE public.mcp_oauth_tokens TO service_role;
GRANT ALL ON SEQUENCE public.mcp_oauth_tokens_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.cleanup_mcp_oauth()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  DELETE FROM public.mcp_oauth_tokens
  WHERE id IN (
    SELECT id FROM public.mcp_oauth_tokens
    WHERE refresh_expires_at < pg_catalog.now()
    LIMIT 500
  );

  DELETE FROM public.mcp_oauth_tokens
  WHERE id IN (
    SELECT id FROM public.mcp_oauth_tokens
    WHERE revoked_at IS NOT NULL
      AND revoked_at < pg_catalog.now() - interval '7 days'
    LIMIT 500
  );

  DELETE FROM public.mcp_oauth_codes
  WHERE code_hash IN (
    SELECT code_hash FROM public.mcp_oauth_codes
    WHERE expires_at < pg_catalog.now()
    LIMIT 500
  );

  DELETE FROM public.mcp_oauth_clients
  WHERE client_id IN (
    SELECT c.client_id
    FROM public.mcp_oauth_clients c
    WHERE c.created_at < pg_catalog.now() - interval '7 days'
      AND NOT EXISTS (
        SELECT 1 FROM public.mcp_oauth_tokens t WHERE t.client_id = c.client_id
      )
      AND NOT EXISTS (
        SELECT 1 FROM public.mcp_oauth_codes d
        WHERE d.client_id = c.client_id AND d.expires_at >= pg_catalog.now()
      )
    LIMIT 200
  );
END;
$$;

ALTER FUNCTION public.cleanup_mcp_oauth() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.cleanup_mcp_oauth() FROM PUBLIC;
GRANT ALL ON FUNCTION public.cleanup_mcp_oauth() TO service_role;

INSERT INTO public.cron_tasks (
  name,
  description,
  task_type,
  target,
  hour_interval,
  run_at_minute,
  enabled
) VALUES (
  'cleanup_mcp_oauth',
  'Delete expired MCP OAuth tokens, codes, and unused clients',
  'function',
  'public.cleanup_mcp_oauth()',
  1,
  17,
  true
);
