CREATE TABLE public.cli_usage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  cli_version text NOT NULL,
  command text NOT NULL DEFAULT '',
  node_version text NOT NULL DEFAULT '',
  os_platform text NOT NULL DEFAULT '',
  apikey_id uuid NULL,
  org_id uuid NULL,
  source text NOT NULL DEFAULT 'config'
);
CREATE INDEX cli_usage_created_at_idx ON public.cli_usage (created_at DESC);
CREATE INDEX cli_usage_cli_version_idx ON public.cli_usage (cli_version);
CREATE INDEX cli_usage_apikey_id_idx ON public.cli_usage (apikey_id) WHERE apikey_id IS NOT NULL;

ALTER TABLE public.cli_usage OWNER TO postgres;
ALTER TABLE public.cli_usage ENABLE ROW LEVEL SECURITY;

-- System-managed: deny user-facing roles explicitly
CREATE POLICY "Deny select on cli_usage" ON public.cli_usage AS RESTRICTIVE FOR SELECT TO authenticated, anon USING (false);
CREATE POLICY "Deny insert on cli_usage" ON public.cli_usage AS RESTRICTIVE FOR INSERT TO authenticated, anon WITH CHECK (false);
CREATE POLICY "Deny update on cli_usage" ON public.cli_usage AS RESTRICTIVE FOR UPDATE TO authenticated, anon USING (false);
CREATE POLICY "Deny delete on cli_usage" ON public.cli_usage AS RESTRICTIVE FOR DELETE TO authenticated, anon USING (false);

GRANT ALL ON TABLE public.cli_usage TO service_role;
GRANT ALL ON SEQUENCE public.cli_usage_id_seq TO service_role;
