#!/usr/bin/env bun
/**
 * Build the minified Cloudflare Snippet from cloudflare_workers/snippet/index.js.
 *
 * Cloudflare Snippets are limited to 32 KB, so the readable source cannot be
 * pasted as-is. This writes a minified, versioned copy next to it.
 *
 * Usage:
 *   bun scripts/snippet/build-snippet.ts          # write index.min.js
 *   bun scripts/snippet/build-snippet.ts --check  # fail if stale or > 32 KB
 */
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

const MAX_BYTES = 32 * 1024
const root = resolve(import.meta.dir, '../..')
const sourcePath = resolve(root, 'cloudflare_workers/snippet/index.js')
const outPath = resolve(root, 'cloudflare_workers/snippet/index.min.js')
const check = process.argv.includes('--check')

const source = readFileSync(sourcePath, 'utf8')
const sourceHash = createHash('sha256').update(source).digest('hex').slice(0, 12)
const { version } = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'))

const result = await Bun.build({
  entrypoints: [sourcePath],
  minify: true,
  target: 'browser',
  format: 'esm',
})
if (!result.success) {
  for (const log of result.logs)
    console.error(log)
  process.exit(1)
}

const header = `// Capgo Cloudflare Snippet v${version} source:${sourceHash} — GENERATED by scripts/snippet/build-snippet.ts, do not edit\n`
const output = header + (await result.outputs[0].text())
const bytes = Buffer.byteLength(output)
const sizeLabel = `${(bytes / 1024).toFixed(2)} KB / ${MAX_BYTES / 1024} KB`

if (bytes > MAX_BYTES) {
  console.error(`Snippet too large: ${sizeLabel}`)
  process.exit(1)
}

if (check) {
  const existing = existsSync(outPath) ? readFileSync(outPath, 'utf8') : ''
  if (!existing.includes(`source:${sourceHash}`)) {
    console.error('cloudflare_workers/snippet/index.min.js is stale. Run: bun run build:snippet')
    process.exit(1)
  }
  console.log(`Snippet OK: ${sizeLabel}`)
}
else {
  writeFileSync(outPath, output)
  console.log(`Wrote ${outPath} (${sizeLabel}, source:${sourceHash})`)
}
